/* Description: Pressing BUTTON1 toggles RED LED and pressing BUTTON2
 * the GREEN LED. Implemented using interrupts.
 * Adapted from code listing 6.10 (p. 100) from the textbook.
 *
 * Author: Giri Prabhu
 * Modified: Naga Kandasamy, July 16, 2019
*******************************************************************************/

/* DriverLib includes. */
#include <ti/devices/msp432p4xx/driverlib/driverlib.h>

/* Standard includes. */
#include <stdint.h>
#include <stdbool.h>

int
main (void)
{
    /* Stop Watchdog timer. */
    MAP_WDT_A_holdTimer ();

    /* Configure the output GPIO pins driving the LEDs. */
    GPIO_setAsOutputPin (GPIO_PORT_P2, GPIO_PIN0 | GPIO_PIN1);
    GPIO_setOutputLowOnPin (GPIO_PORT_P2, GPIO_PIN0 | GPIO_PIN1);

    /* Configure input GPIO pins, P1.1 for BUTTON1 and BUTTON2 P1.4. */
    GPIO_setAsInputPinWithPullUpResistor (GPIO_PORT_P1, GPIO_PIN1 | GPIO_PIN4);
    GPIO_interruptEdgeSelect (GPIO_PORT_P1, GPIO_PIN1 | GPIO_PIN4, GPIO_LOW_TO_HIGH_TRANSITION);
    GPIO_clearInterruptFlag (GPIO_PORT_P1, GPIO_PIN1 | GPIO_PIN4);
    GPIO_enableInterrupt (GPIO_PORT_P1, GPIO_PIN1 | GPIO_PIN4);
    Interrupt_enableInterrupt (INT_PORT1);
    Interrupt_enableMaster ();

    while (1);
}

/* ISR to handle IRQs generated by pins in PORT1. */
void
PORT1_IRQHandler (void)
{
    uint16_t status = GPIO_getEnabledInterruptStatus (GPIO_PORT_P1);
    GPIO_clearInterruptFlag (GPIO_PORT_P1, status);

    /* Check for the correct pin that generated the interrupt. */
    if (status & GPIO_PIN1)
        GPIO_toggleOutputOnPin (GPIO_PORT_P2, GPIO_PIN0);
    else if (status & GPIO_PIN4)
        GPIO_toggleOutputOnPin (GPIO_PORT_P2, GPIO_PIN1);

    return;
}
